app:
  name: api-server-manager

http-server:
    port: 8080

database:
  host: localhost
  port: 5432
  user: happy_miner
  password: happy_miner
  name: server_manager


vault:
  address: localhost
  port: 8200
  token: root
  mount-path: secret
  connections:
    path: ssh-keys
