version: '3.9'

services:
  postgres:
    image: postgres:17.3
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: happy_miner
      POSTGRES_PASSWORD: happy_miner
      POSTGRES_DB: server_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
