version: '3.9'

services:
  postgres:
    image: postgres:17.3
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: happy_miner
      POSTGRES_PASSWORD: happy_miner
      POSTGRES_DB: server_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network


  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: "server -dev"

volumes:
  postgres_data:
  vault-data:

networks:
  postgres_network:
