// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imDrOne/minecraft-server-manager/internal/app/connections (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination mock_test.go -package connections . Repository
//

// Package connections is a generated GoMock package.
package connections

import (
	context "context"
	reflect "reflect"

	connections "github.com/imDrOne/minecraft-server-manager/internal/domain/connections"
	connections0 "github.com/imDrOne/minecraft-server-manager/internal/infrastructure/connections"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindById mocks base method.
func (m *MockRepository) FindById(arg0 context.Context, arg1 int64) (*connections.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0, arg1)
	ret0, _ := ret[0].(*connections.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockRepositoryMockRecorder) FindById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockRepository)(nil).FindById), arg0, arg1)
}

// FindByNodeId mocks base method.
func (m *MockRepository) FindByNodeId(arg0 context.Context, arg1 int64) ([]connections.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNodeId", arg0, arg1)
	ret0, _ := ret[0].([]connections.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNodeId indicates an expected call of FindByNodeId.
func (mr *MockRepositoryMockRecorder) FindByNodeId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNodeId", reflect.TypeOf((*MockRepository)(nil).FindByNodeId), arg0, arg1)
}

// Save mocks base method.
func (m *MockRepository) Save(arg0 context.Context, arg1 int64, arg2 connections0.CreateConn) (*connections.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(*connections.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), arg0, arg1, arg2)
}
