// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imDrOne/minecraft-server-manager/internal/service/connections (interfaces: ConnectionRepository)
//
// Generated by this command:
//
//	mockgen -destination mock_conn_repo_test.go -package connections . ConnectionRepository
//

// Package connections is a generated GoMock package.
package connections

import (
	context "context"
	reflect "reflect"

	connections "github.com/imDrOne/minecraft-server-manager/internal/domain/connections"
	db "github.com/imDrOne/minecraft-server-manager/internal/infrastructure/connections/db"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionRepository is a mock of ConnectionRepository interface.
type MockConnectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionRepositoryMockRecorder
	isgomock struct{}
}

// MockConnectionRepositoryMockRecorder is the mock recorder for MockConnectionRepository.
type MockConnectionRepositoryMockRecorder struct {
	mock *MockConnectionRepository
}

// NewMockConnectionRepository creates a new mock instance.
func NewMockConnectionRepository(ctrl *gomock.Controller) *MockConnectionRepository {
	mock := &MockConnectionRepository{ctrl: ctrl}
	mock.recorder = &MockConnectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionRepository) EXPECT() *MockConnectionRepositoryMockRecorder {
	return m.recorder
}

// FindById mocks base method.
func (m *MockConnectionRepository) FindById(arg0 context.Context, arg1 int64) (*connections.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0, arg1)
	ret0, _ := ret[0].(*connections.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockConnectionRepositoryMockRecorder) FindById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockConnectionRepository)(nil).FindById), arg0, arg1)
}

// FindByNodeId mocks base method.
func (m *MockConnectionRepository) FindByNodeId(ctx context.Context, id int64) ([]connections.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNodeId", ctx, id)
	ret0, _ := ret[0].([]connections.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNodeId indicates an expected call of FindByNodeId.
func (mr *MockConnectionRepositoryMockRecorder) FindByNodeId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNodeId", reflect.TypeOf((*MockConnectionRepository)(nil).FindByNodeId), ctx, id)
}

// Save mocks base method.
func (m *MockConnectionRepository) Save(arg0 context.Context, arg1 int64, arg2 db.CreateConn) (*connections.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2)
	ret0, _ := ret[0].(*connections.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockConnectionRepositoryMockRecorder) Save(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConnectionRepository)(nil).Save), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockConnectionRepository) Update(ctx context.Context, id int64, updateConn db.UpdateConn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, updateConn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockConnectionRepositoryMockRecorder) Update(ctx, id, updateConn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConnectionRepository)(nil).Update), ctx, id, updateConn)
}
